Question Revision with New Notes on South Korea's Response.
evolverine/covid-19-anki-deck pull request #13
Opened 2020-03-27 05:13 UTC by kiba

Future proof the question about numbers reported during the pandemic. Added a new note on how testing equipment shortage affect the accuracy of official numbers.

Added questions about how South Korea manage the crisis so well in question & answer format as well cloze deletion.

Note: There is weirdness with the delays because I have different delays setting and had to set it back for export and commit. CrowdAnki is very inconvenient.

2020-03-27 13:09 UTC, evolverine requested changes
Thank you for the pull request! I hope the changes I'm suggesting make sense, please let me know if you have any questions.

2020-03-27 13:09 UTC, evolverine commented on deck.json
> +                "How does the shortage of testing equipment affects the accuracy of official statistics in the COVID-19 pandemic?",
```suggestion
                "How does the shortage of testing equipment affect the accuracy of official statistics in the COVID-19 pandemic?",
```

2020-03-27 13:09 UTC, evolverine commented on deck.json
> +                "Not enough supply means it is not possible to detect every cases of COVID-19.",
```suggestion
                "It means it isn't possible to detect every case of COVID-19.",
```

2020-03-27 13:09 UTC, evolverine commented on deck.json
> +            ],
It looks like you (or CrowdAnki?) removed two fields from the note type (apart from "Front", "Back" and "Source", which I see here, it should also have a field called "Context" and one called "Include Reverse"). This ended up changing its "crowdanki_uuid" property as well. If you could convert your new notes to the original note type, called "Front <-> Back Source Context" (except for the Cloze deletions, of course) it would be great for keeping the model as simple as possible.

2020-03-27 13:09 UTC, evolverine commented on deck.json
> +                "How did South Korea flatten the curve?(tentative March 2020)",
In general, I [try to avoid long answers](https://www.supermemo.com/en/articles/20rules). Maybe we could split this into a few cards? My suggestion would be something like this:

1. Front: "Speed of intervention"
Back: "Quick emergency intervention"
Source: ...
Context: "South Korea's success in flattening the curve"

2. Front: "Testing"
Back: "Broad and quick testing"
Source: ...
Context: "South Korea's success in flattening the curve"

3. Front: "Tracing"
Back: "Tracing the journeys of the diagnosed, testing everyone who came into contact with them, and quarantining the infected"
Source: ...
Context: "South Korea's success in flattening the curve"

4. Front: "Trust"
Back: "Public trusted the authorities and cooperated"
Source: ...
Context: "South Korea's success in flattening the curve"

I also realize that before these questions we ought to define the terms and concepts around "flattening the curve" and "tracing" for those who are not familiar with them.

2020-03-27 13:09 UTC, evolverine commented on deck.json
> +                "How did South Korea flatten the curve?(tentative March 2020)<div><br></div><div><div>- {{c1::Quick emergency response.}}</div><div>- {{c2::Test people in a safe manner as often and q
With the changes above, the cloze deletion could be simplified to
```suggestion
                "South Korea's initial success in flattening the curve: {{c1::speed of intervention}}, {{c2::broad and quick testing}}, {{c3::comprehensive tracing.}}, {{c4::public trust and cooperation}}</div></div>",
```

2020-03-27 13:09 UTC, evolverine commented on deck.json
> +            "note_model_uuid": "278ee8b9-6fe6-11ea-b26e-80e82c59ddd1",
I've just added a cloze question in the deck (which you will receive by running `git pull upstream`) which also has a source field; please use that note type for this question.

2020-03-27 13:12 UTC, kiba commented on deck.json
> +                "Not enough supply means it is not possible to detect every cases of COVID-19.",
Looks good to me.

2020-03-27 13:13 UTC, evolverine commented
Before working on this the best thing would be to pull the latest changes from this deck `git pull upstream` or `git fetch upstream` then `git merge upstream/master`, whichever is best for you.

Note that if you get conflicts and they're difficult to solve, there's another, possibly easier way to go about them: you can move the cards you created and changed to a new folder, then re-import this deck via CrowdAnki (which should maintain your scheduling information), and then put your cards back / edit the ones that are changed (and apply any changes suggested above that make sense to you) and do an export via CrowdAnki.

2020-03-27 13:14 UTC, kiba commented on deck.json
> +                "How did South Korea flatten the curve?(tentative March 2020)",
I didn't think it was possible to do this. I will implement hen I get the chance.

2020-03-27 13:15 UTC, kiba commented on deck.json
> +            ],
It was a card type I used. I'll change it to match.

2020-03-27 20:21 UTC, kiba commented
Oops. Look like I didn't know what I was doing with the merge. First time that it was something so complicated.  I'll have to revert and redo them properly.

2020-03-29 01:32 UTC, closed without merging

2020-03-29 09:18 UTC, evolverine commented
👍 good luck, and let me know if I can help